[package]
name = "gotr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
git2 = "0.18.1"
iced = {version = "0.10.0", features = ["async-std", "debug"]}
